### ISSUE TITLE
Error 1027: Too many requests

### ISSUE THREAD

**Issue by serge2015** [TelegramPlayGround/Free-Movie-Series-DB-API#12]
**The issue is with the**
- [ ] Telegram Bot
- [x] API

**Describe the bug**
When searching by IMDB_ID, I get a 429 error (too many requests) on my site and it also says my site "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**To Reproduce**
Steps to reproduce the behavior: I load a page that displays the information pulled from the search by IMDB ID.

**Expected behavior**
Content should load automatically, just as it did for me for the past week when testing my site in development.

**Screenshots**
![image](https://github.com/user-attachments/assets/6b9ef78d-6df1-4a44-a18b-d3334bf49b0e)

**(please complete the following information):**
 - OS: Windows 11 Home
 - Device: Chrome Version 128.0.6613.86

**Comment by SpEcHiDe** [comment]
CloudflareWorkers only allows 10000 requests per day. The limit gets reset daily. So, you can try again the next day.
